### ISSUE TITLE
Can I use on a MKS Monster8 ?

### ISSUE THREAD

**Issue by themacboy** [Mellow-3D/Klipper-CAN-Toolboards#2]
Can it be used directlly connected to CANbus on MKS Monster8 board? 
Can you give a few instructions or record a video? 

Thx in advance

**Comment by MarvinBeym** [comment]
In theory since recently `yes` => https://www.klipper3d.org/CANBUS.html#usb-to-can-bus-bridge-mode

It may or may not work. This change is still somewhat experimental, as it may not work on all boards immediately or flawless.

However using a UTOC or similar USB to CAN adapter is still recommended as going through the mcu first is a severe bottleneck and may cause other issues like klipper shutting down because no bandwidth is available
